export default {
	SET_EXPENSES: 'EXPENSE/SET_EXPENSES',
	SET_DATES: 'EXPENSE/SET_DATES',
	SET_LOADING: 'EXPENSE/SET_LOADING',
	REMOVE_EXPENSES: 'EXPENSE/REMOVE_EXPENSES',
	REMOVE_DATES: 'EXPENSE/REMOVE_DATES',
	REMOVE_LOADING: 'EXPENSE/REMOVE_LOADING',
}
