export default {
	SET_EXPENSE: 'EXPENSE/SET_EXPENSE',
	SET_EXPENSES: 'EXPENSE/SET_EXPENSES',
	SET_LOADING: 'EXPENSE/SET_LOADING',
	SET_MESSAGE: 'AUTH/SET_MESSAGE',
	REMOVE_EXPENSE: 'EXPENSE/REMOVE_EXPENSE',
	REMOVE_EXPENSES: 'EXPENSE/REMOVE_EXPENSES',
	REMOVE_LOADING: 'EXPENSE/REMOVE_LOADING',
	REMOVE_MESSAGE: 'AUTH/REMOVE_MESSAGE',
}
