export default {
	SET_UID: 'AUTH/SET_UID',
	SET_USER: 'AUTH/SET_USER',
	SET_LOADING: 'AUTH/SET_LOADING',
	REMOVE_UID: 'AUTH/REMOVE_UID',
	REMOVE_USER: 'AUTH/REMOVE_USER',
	REMOVE_LOADING: 'AUTH/REMOVE_LOADING',
}
